name: dynamic_marker
description: "Google Map er upor jekono Flutter widget diye dynamic marker overlay korar package."
version: 0.0.5
homepage: https://github.com/NafimAhmed/map_marker2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0

flutter:
  uses-material-design: false
